package constant

const (
	USER_TYPE_USER  = "USER"
	USER_TYPE_ADM   = "ADM"
	USER_TYPE_SUPER = "SUPER"
	USER_BLOCKED    = "BLOCKED"
	USER_SUSPENDED  = "SUSPENDED"
	COMPANY         = "COMPANY"
	REGIONAL        = "REGIONAL"
	SUPERVISOR      = "SUPERVISOR"
	COLLECTOR       = "COLLECTOR"
	SELLER          = "SELLER"

	MAX_RECORDS = " OFFSET 0 LIMIT 1000 "

	CONTEXT_ID = 1
)
